<?php

declare(strict_types=1);

namespace App\Livewire\Admin\Grading;

use App\Livewire\Concerns\DispatchesCollegeToasts;
use App\Models\GradePoint;
use Illuminate\Contracts\View\View;
use Illuminate\Validation\Rule;
use Livewire\Attributes\On;
use Livewire\Component;
use Livewire\WithPagination;

class GradePointsPage extends Component
{
    use DispatchesCollegeToasts;
    use WithPagination;

    public string $grade = '';

    public string $min_score = '';

    public string $max_score = '';

    public string $points = '';

    public ?int $editingId = null;

    public ?int $deletingId = null;

    public array $defaultGradePoints = [];

    public bool $showAutoGenerateModal = false;

    public function saveRow(): void
    {
        $rules = [
            'grade' => [
                'required',
                'string',
                'max:32',
                $this->editingId 
                    ? Rule::unique('grade_points', 'grade')->ignore($this->editingId)
                    : 'unique:grade_points,grade',
            ],
            'min_score' => ['required', 'numeric', 'min:0', 'max:100'],
            'max_score' => ['required', 'numeric', 'gte:min_score', 'max:100'],
            'points' => ['required', 'numeric', 'min:0', 'max:10'],
        ];

        $this->validate($rules);

        if ($this->editingId) {
            $gp = GradePoint::query()->findOrFail($this->editingId);
            $gp->update([
                'grade' => strtoupper(trim($this->grade)),
                'min_score' => (float) $this->min_score,
                'max_score' => (float) $this->max_score,
                'points' => (float) $this->points,
            ]);
            $this->collegeToast(__('Grade band updated.'));
            $this->cancelEdit();
        } else {
            GradePoint::query()->create([
                'grade' => strtoupper(trim($this->grade)),
                'min_score' => (float) $this->min_score,
                'max_score' => (float) $this->max_score,
                'points' => (float) $this->points,
            ]);
            $this->collegeToast(__('Grade band added.'));
            $this->reset(['grade', 'min_score', 'max_score', 'points']);
        }

        $this->resetPage();
    }

    public function edit(int $id): void
    {
        $gp = GradePoint::query()->findOrFail($id);
        $this->editingId = $gp->id;
        $this->grade = $gp->grade;
        $this->min_score = (string) $gp->min_score;
        $this->max_score = (string) $gp->max_score;
        $this->points = (string) $gp->points;
        $this->resetValidation();
    }

    public function cancelEdit(): void
    {
        $this->editingId = null;
        $this->reset(['grade', 'min_score', 'max_score', 'points']);
        $this->resetValidation();
    }

    public function confirmDelete(int $id): void
    {
        $this->deletingId = $id;
        $this->dispatch('open-modal', 'confirm-delete-grade-point-modal');
    }

    public function deleteGradePoint(): void
    {
        if ($this->deletingId === null) {
            return;
        }

        GradePoint::query()->findOrFail($this->deletingId)->delete();
        
        if ($this->editingId === $this->deletingId) {
            $this->cancelEdit();
        }

        $this->deletingId = null;
        $this->collegeToast(__('Grade band deleted.'));
        $this->resetPage();
    }

    #[On('open-auto-generate')]
    public function autoGenerateDefaults(): void
    {
        $this->defaultGradePoints = [
            ['grade' => 'A', 'min_score' => 80.0, 'max_score' => 100.0, 'points' => 4.0, 'selected' => true],
            ['grade' => 'B+', 'min_score' => 75.0, 'max_score' => 79.99, 'points' => 3.5, 'selected' => true],
            ['grade' => 'B', 'min_score' => 70.0, 'max_score' => 74.99, 'points' => 3.0, 'selected' => true],
            ['grade' => 'C+', 'min_score' => 65.0, 'max_score' => 69.99, 'points' => 2.5, 'selected' => true],
            ['grade' => 'C', 'min_score' => 60.0, 'max_score' => 64.99, 'points' => 2.0, 'selected' => true],
            ['grade' => 'D+', 'min_score' => 55.0, 'max_score' => 59.99, 'points' => 1.5, 'selected' => true],
            ['grade' => 'D', 'min_score' => 50.0, 'max_score' => 54.99, 'points' => 1.0, 'selected' => true],
            ['grade' => 'E', 'min_score' => 0.0, 'max_score' => 49.99, 'points' => 0.0, 'selected' => true],
        ];

        $this->showAutoGenerateModal = true;
    }

    public function saveAutoGenerated(): void
    {
        $this->validate([
            'defaultGradePoints.*.grade' => ['required', 'string', 'max:32'],
            'defaultGradePoints.*.min_score' => ['required', 'numeric', 'min:0', 'max:100'],
            'defaultGradePoints.*.max_score' => ['required', 'numeric', 'gte:defaultGradePoints.*.min_score', 'max:100'],
            'defaultGradePoints.*.points' => ['required', 'numeric', 'min:0', 'max:10'],
        ]);

        $insertedCount = 0;
        foreach ($this->defaultGradePoints as $gp) {
            if (! empty($gp['selected'])) {
                GradePoint::query()->updateOrCreate(
                    ['grade' => strtoupper(trim($gp['grade']))],
                    [
                        'min_score' => (float) $gp['min_score'],
                        'max_score' => (float) $gp['max_score'],
                        'points' => (float) $gp['points'],
                    ]
                );
                $insertedCount++;
            }
        }

        $this->showAutoGenerateModal = false;
        $this->collegeToast(__(':count grade bands auto-generated successfully.', ['count' => $insertedCount]));
        $this->resetPage();
    }

    public function render(): View
    {
        $rows = GradePoint::query()->orderBy('min_score')->paginate(20);

        return view('livewire.admin.grading.grade-points-page', [
            'rows' => $rows,
        ])->layout('components.layouts.admin', [
            'title' => __('Grade points'),
            'headerTitle' => __('Grade Points Setup'),
            'headerDescription' => __('Configure grade letters, score thresholds, and grade point averages.'),
        ]);
    }
}
